export interface ManualTopic {
  id: string;
  title: string;
  summary: string;
  icon: string;
  steps?: string[];
  details?: string[];
  tips?: string[];
  warning?: string;
  moduleId?: string;
  actionLabel?: string;
  keywords?: string[];
}

export interface ManualSection {
  id: string;
  title: string;
  description: string;
  icon: string;
  topics: ManualTopic[];
}

export const manualSections: ManualSection[] = [
  {
    id: "primeiros-passos",
    title: "Primeiros passos",
    description: "Prepare o programa e faça sua primeira projeção.",
    icon: "mdi-rocket-launch-outline",
    topics: [
      {
        id: "interface",
        title: "Conheça a interface",
        summary: "Acesse músicas, Bíblia, liturgia, mídias e configurações pelo menu lateral.",
        icon: "mdi-view-dashboard-outline",
        details: [
          "O botão no canto superior esquerdo abre ou recolhe o menu lateral.",
          "A Página Inicial reúne atalhos, coletâneas recentes e conteúdos mais usados.",
          "Os módulos abrem na área central sem interromper uma projeção ativa.",
          "O player inferior concentra reprodução, volume e controles do conteúdo em execução.",
        ],
        moduleId: "home",
        actionLabel: "Ir para a Página Inicial",
        keywords: ["início", "menu", "sidebar", "player", "navegação"],
      },
      {
        id: "configuracao-inicial",
        title: "Configuração inicial recomendada",
        summary: "Defina idioma, aparência, telas e mídia antes da programação.",
        icon: "mdi-tune-variant",
        steps: [
          "Em Configurações > Aparência, escolha o tema e a cor principal.",
          "Em Geral, confira idioma e preferências de funcionamento.",
          "Em Mídia, ajuste volume, transições e comportamento da reprodução.",
          "Em Projeção, escolha a tela principal e o monitor de retorno, se houver.",
          "Faça um teste com uma música ou versículo.",
        ],
        tips: ["Conecte os monitores antes de abrir o aplicativo para facilitar a detecção."],
        moduleId: "config",
        actionLabel: "Abrir Configurações",
        keywords: ["instalação", "idioma", "tema", "monitor", "tela", "som"],
      },
      {
        id: "primeira-projecao",
        title: "Faça uma projeção de teste",
        summary: "Valide a saída, a legibilidade e os controles antes do culto.",
        icon: "mdi-projector-screen-outline",
        steps: [
          "Abra uma música, um hino ou a Bíblia e inicie a apresentação.",
          "Use os controles para avançar e voltar entre slides ou versos.",
          "Confira a tela principal e o monitor de retorno.",
          "Pressione Esc para encerrar ou ocultar a projeção, conforme o conteúdo.",
        ],
        warning: "Teste vídeos com áudio no equipamento do evento; cabos, drivers e saídas podem alterar o resultado.",
        keywords: ["teste", "projetor", "slide", "esc", "saída"],
      },
    ],
  },
  {
    id: "musicas-hinos",
    title: "Músicas e hinos",
    description: "Localize letras, reproduza áudios e apresente canções.",
    icon: "mdi-music-note-outline",
    topics: [
      {
        id: "buscar-musica",
        title: "Encontre e apresente uma música",
        summary: "Pesquise pelo título e abra a letra ou o áudio da biblioteca.",
        icon: "mdi-magnify",
        steps: [
          "Abra Músicas ou pressione Ctrl+F.",
          "Digite parte do título e selecione o resultado.",
          "Escolha a forma de reprodução disponível.",
          "Durante a apresentação, navegue pelos controles de slides.",
        ],
        moduleId: "musics",
        actionLabel: "Abrir Músicas",
        keywords: ["louvor", "letra", "canção", "áudio", "pesquisa", "ctrl f"],
      },
      {
        id: "hinarios",
        title: "Use os hinários",
        summary: "Consulte a edição atual ou o Hinário Adventista de 1996.",
        icon: "mdi-book-music-outline",
        steps: [
          "Abra o Hinário Adventista no menu.",
          "Pesquise pelo número ou nome do hino.",
          "Selecione a opção de letra ou mídia disponível.",
          "Inicie a apresentação e navegue pelas estrofes.",
        ],
        tips: ["A edição de 1996 fica em um módulo separado para evitar confusão entre numerações."],
        moduleId: "hymnal",
        actionLabel: "Abrir Hinário",
        keywords: ["hino", "hinário", "1996", "número", "estrofe"],
      },
      {
        id: "coletaneas",
        title: "Navegue por álbuns e coletâneas",
        summary: "Explore conteúdos agrupados por álbum, projeto ou coleção.",
        icon: "mdi-album",
        details: [
          "Abra uma coletânea para ver capa, faixas e recursos disponíveis.",
          "Itens não sincronizados podem depender da Biblioteca Local para uso offline.",
        ],
        moduleId: "collections",
        actionLabel: "Abrir Álbuns",
        keywords: ["álbum", "coletânea", "faixa", "capa"],
      },
      {
        id: "letra-personalizada",
        title: "Crie uma letra personalizada",
        summary: "Adicione uma música ou texto que ainda não existe na biblioteca.",
        icon: "mdi-pencil-plus-outline",
        steps: [
          "Abra o Criador de Músicas.",
          "Informe o título e cole ou digite a letra.",
          "Separe estrofes e refrões com linhas em branco.",
          "Revise, salve e abra a música para apresentar.",
        ],
        moduleId: "custom_song",
        actionLabel: "Criar música",
        keywords: ["personalizada", "criar", "editar", "estrofe", "refrão"],
      },
    ],
  },
  {
    id: "biblia",
    title: "Bíblia",
    description: "Pesquise passagens e projete versos com rapidez.",
    icon: "mdi-book-cross",
    topics: [
      {
        id: "passagem-biblica",
        title: "Abra uma passagem bíblica",
        summary: "Escolha livro, capítulo e verso ou use a busca rápida.",
        icon: "mdi-book-open-page-variant-outline",
        steps: [
          "Abra a Bíblia pelo menu ou pressione Ctrl+B.",
          "Selecione livro, capítulo e clique no verso para projetar.",
          "Use as setas esquerda e direita para navegar entre versos.",
          "Use Delete para limpar a exibição bíblica.",
        ],
        tips: ["Confirme a referência e a versão bíblica antes de projetar."],
        moduleId: "bible",
        actionLabel: "Abrir Bíblia",
        keywords: ["versículo", "verso", "capítulo", "livro", "ctrl b", "delete"],
      },
      {
        id: "aparencia-biblia",
        title: "Ajuste a aparência dos versos",
        summary: "Personalize fundo, cores e informações da projeção bíblica.",
        icon: "mdi-palette-outline",
        details: [
          "Use as configurações da Bíblia para definir cores do texto e do fundo.",
          "Ajuste o conteúdo do monitor de retorno conforme a necessidade.",
          "Valide contraste e tamanho do texto à distância.",
        ],
        warning: "A tela do operador pode parecer mais clara que o projetor; sempre confira a saída real.",
        moduleId: "bible",
        actionLabel: "Configurar Bíblia",
        keywords: ["fonte", "cor", "fundo", "contraste", "referência"],
      },
    ],
  },
  {
    id: "liturgia-midias",
    title: "Liturgia e mídias",
    description: "Organize o culto e apresente arquivos externos.",
    icon: "mdi-playlist-play",
    topics: [
      {
        id: "liturgia",
        title: "Monte a liturgia",
        summary: "Organize os itens do culto em uma sequência pronta para operar.",
        icon: "mdi-format-list-numbered",
        steps: [
          "Abra Liturgia e crie ou selecione uma programação.",
          "Adicione músicas, passagens e outros itens.",
          "Reordene os itens de acordo com o roteiro.",
          "Revise e abra cada item diretamente pela liturgia durante o evento.",
        ],
        moduleId: "liturgy",
        actionLabel: "Abrir Liturgia",
        keywords: ["roteiro", "ordem", "culto", "programação", "sequência"],
      },
      {
        id: "apresentacoes",
        title: "Apresente PDFs e apresentações",
        summary: "Abra arquivos e navegue pelas páginas na tela de saída.",
        icon: "mdi-presentation",
        steps: [
          "Abra Apresentações e escolha o arquivo compatível.",
          "Aguarde o carregamento e confira a primeira página.",
          "Use os controles para avançar, voltar e encerrar.",
        ],
        warning: "Abra arquivos grandes antes do evento para detectar incompatibilidades e aguardar o processamento.",
        moduleId: "presentation",
        actionLabel: "Abrir Apresentações",
        keywords: ["pdf", "powerpoint", "ppt", "arquivo", "página"],
      },
      {
        id: "midia-externa",
        title: "Reproduza mídia externa",
        summary: "Use áudio, vídeo ou imagem que não faz parte da biblioteca.",
        icon: "mdi-file-play-outline",
        steps: [
          "Abra Mídia Externa e selecione um arquivo.",
          "Confirme a prévia e a saída de áudio.",
          "Inicie a reprodução e use os controles do player.",
          "Interrompa a mídia antes de abrir o próximo item.",
        ],
        tips: ["Mantenha os arquivos no computador; pendrives podem desconectar ou carregar lentamente."],
        moduleId: "external_media",
        actionLabel: "Abrir Mídia Externa",
        keywords: ["vídeo", "áudio", "imagem", "mp4", "pendrive"],
      },
    ],
  },
  {
    id: "projecao",
    title: "Projeção e retorno",
    description: "Configure monitores e controle o que cada tela exibe.",
    icon: "mdi-monitor-multiple",
    topics: [
      {
        id: "configurar-telas",
        title: "Configure as telas",
        summary: "Escolha a saída principal e um monitor de retorno, se disponível.",
        icon: "mdi-monitor-cog",
        steps: [
          "No sistema operacional, configure as telas no modo Estender.",
          "Abra Configurações > Projeção.",
          "Selecione a tela de apresentação, evitando a tela do operador.",
          "Configure o monitor de retorno e suas informações, se usado.",
          "Projete um conteúdo de teste e confira cada tela.",
        ],
        warning: "No modo Duplicar, operador e público podem ver a mesma imagem. Para controle independente, use Estender.",
        moduleId: "config",
        actionLabel: "Configurar Projeção",
        keywords: ["segunda tela", "monitor", "retorno", "duplicar", "estender", "projetor"],
      },
      {
        id: "operar-projecao",
        title: "Controle uma apresentação ativa",
        summary: "Avance, volte, pause ou encerre o conteúdo com segurança.",
        icon: "mdi-remote",
        details: [
          "Use anterior e próximo para trocar slides, páginas ou versos.",
          "O player permite pausar e retomar mídias com duração.",
          "Esc encerra ou oculta a projeção quando aceito pelo conteúdo.",
          "O retorno pode mostrar o item atual e informações do próximo.",
        ],
        keywords: ["avançar", "voltar", "pausar", "encerrar", "esc", "slide"],
      },
    ],
  },
  {
    id: "biblioteca",
    title: "Biblioteca local",
    description: "Prepare dados e arquivos para trabalhar offline.",
    icon: "mdi-database-sync-outline",
    topics: [
      {
        id: "sincronizar",
        title: "Sincronize a biblioteca",
        summary: "Baixe dados, capas e recursos necessários para uso local.",
        icon: "mdi-cloud-download-outline",
        steps: [
          "Conecte o computador à internet.",
          "Abra Biblioteca Local ou pressione Ctrl+L.",
          "Inicie a sincronização necessária.",
          "Mantenha o aplicativo aberto até a conclusão.",
          "Teste o conteúdo importante sem depender da rede.",
        ],
        warning: "Não desligue o computador durante uma gravação ou atualização da biblioteca.",
        moduleId: "sync",
        actionLabel: "Abrir Biblioteca Local",
        keywords: ["sincronizar", "baixar", "offline", "banco de dados", "ctrl l"],
      },
      {
        id: "preparar-offline",
        title: "Prepare-se para usar sem internet",
        summary: "Baixe e teste todo o conteúdo da programação.",
        icon: "mdi-cloud-off-outline",
        details: [
          "Sincronize antes de ir a um local com conexão instável.",
          "Abra músicas, vídeos e apresentações planejados para confirmar os arquivos.",
          "Mantenha uma cópia local dos arquivos externos e do roteiro.",
          "Faça atualizações do aplicativo fora do horário de uso crítico.",
        ],
        keywords: ["offline", "internet", "backup", "evento", "segurança"],
      },
    ],
  },
  {
    id: "controle-remoto",
    title: "Controle remoto",
    description: "Opere recursos por outro dispositivo na rede local.",
    icon: "mdi-cellphone-link",
    topics: [
      {
        id: "ativar-remoto",
        title: "Ative o controle remoto",
        summary: "Conecte um celular ou tablet pelo endereço ou QR Code.",
        icon: "mdi-qrcode-scan",
        steps: [
          "Abra Configurações > Controle remoto.",
          "Ative o servidor e escolha a rede correta.",
          "Salve e confirme o status Servidor ativo.",
          "No dispositivo na mesma rede, leia o QR Code ou abra o endereço exibido.",
          "Informe a senha, se exigida, e teste os comandos.",
        ],
        tips: ["Prefira uma rede local estável e restrita à equipe."],
        moduleId: "config",
        actionLabel: "Configurar Controle remoto",
        keywords: ["celular", "tablet", "rede", "wifi", "qr code", "senha", "servidor"],
      },
      {
        id: "seguranca-remoto",
        title: "Proteja o acesso remoto",
        summary: "Use senha e compartilhe o acesso apenas com a equipe.",
        icon: "mdi-shield-lock-outline",
        details: [
          "Ative a exigência de senha e evite senhas fáceis em redes públicas.",
          "Pare o servidor quando o recurso não estiver em uso.",
          "Se houver acesso desconhecido, altere a senha e reinicie o servidor.",
        ],
        warning: "Quem tem acesso pode interferir na apresentação. Revise a conexão antes de iniciar.",
        keywords: ["segurança", "senha", "permissão", "rede pública", "desativar"],
      },
    ],
  },
  {
    id: "utilitarios",
    title: "Utilitários",
    description: "Use ferramentas de apoio em programações especiais.",
    icon: "mdi-tools",
    topics: [
      {
        id: "relogio",
        title: "Relógio",
        summary: "Projete horário ou cronômetro com aparência personalizada.",
        icon: "mdi-clock-outline",
        details: ["Configure cores, fundo e formato antes de projetar.", "Use em intervalos, contagens de início ou avisos de horário."],
        moduleId: "clock",
        actionLabel: "Abrir Relógio",
        keywords: ["hora", "cronômetro", "tempo", "intervalo"],
      },
      {
        id: "contador",
        title: "Contador",
        summary: "Mostre uma contagem na tela para atividades e eventos.",
        icon: "mdi-counter",
        details: ["Defina o valor e a aparência.", "Teste incremento, redução e reinício antes da atividade."],
        moduleId: "counter",
        actionLabel: "Abrir Contador",
        keywords: ["contagem", "número", "incrementar", "placar"],
      },
      {
        id: "sorteio",
        title: "Sorteio",
        summary: "Realize sorteios animados de nomes ou números.",
        icon: "mdi-dice-multiple-outline",
        details: ["Cadastre e revise os participantes.", "Configure a aparência e teste antes do sorteio oficial."],
        moduleId: "random",
        actionLabel: "Abrir Sorteio",
        keywords: ["nomes", "números", "participantes", "aleatório"],
      },
      {
        id: "animacoes",
        title: "Animações",
        summary: "Exiba recursos visuais de apoio quando disponíveis.",
        icon: "mdi-animation-play-outline",
        details: ["Visualize a animação antes de projetar.", "Use com moderação para manter o foco no conteúdo principal."],
        moduleId: "animation",
        actionLabel: "Abrir Animações",
        keywords: ["efeito", "visual", "animação", "tela"],
      },
    ],
  },
  {
    id: "operacao-avancada",
    title: "Operação avançada",
    description: "Ganhe agilidade com busca rápida, retorno, controle remoto e automações.",
    icon: "mdi-console-network-outline",
    topics: [
      {
        id: "busca-rapida",
        title: "Use a busca rápida",
        summary: "Encontre músicas ou passagens sem abandonar o fluxo da apresentação.",
        icon: "mdi-text-search",
        steps: [
          "Pressione Ctrl+F para abrir a busca de músicas em qualquer área do programa.",
          "Digite parte do título e escolha o resultado desejado.",
          "Para passagens bíblicas, pressione Ctrl+B e informe livro, capítulo ou referência.",
          "Use Esc para fechar a busca quando não quiser abrir nenhum resultado.",
        ],
        tips: ["No macOS, use Command no lugar de Ctrl."],
        keywords: ["busca rápida", "overlay", "pesquisar", "ctrl f", "ctrl b", "música", "bíblia"],
      },
      {
        id: "retorno-avancado",
        title: "Prepare o monitor de retorno",
        summary: "Mostre conteúdo atual, próximo slide, marcadores, cifras e notas para a equipe.",
        icon: "mdi-monitor-eye",
        steps: [
          "Abra Configurações > Projeção e ative o modo monitor de retorno.",
          "Selecione o monitor correto e escolha quais informações auxiliares serão exibidas.",
          "No Criador de Músicas, use o campo Notas para o retorno para lembretes de entrada, tom ou direção.",
          "Linhas iniciadas com // na letra aparecem somente no retorno, permitindo incluir cifras ou orientações sem mostrá-las ao público.",
          "Use Testar monitor de retorno antes da programação para confirmar o posicionamento.",
        ],
        tips: ["Mantenha as notas curtas para que músicos e operadores consigam lê-las rapidamente."],
        moduleId: "config",
        actionLabel: "Configurar monitor de retorno",
        keywords: ["retorno", "notas", "cifras", "próximo slide", "músicos", "marcador"],
      },
      {
        id: "controle-remoto-operacao",
        title: "Opere pelo celular com segurança",
        summary: "Acompanhe o que está no ar, pesquise conteúdo e controle a apresentação pela rede.",
        icon: "mdi-cellphone-wireless",
        steps: [
          "Ative o servidor em Configurações > Controle remoto e conecte o celular pelo QR Code.",
          "Escolha o perfil Apresentador para comandos básicos ou Operador para acesso completo.",
          "Acompanhe título, conteúdo atual, próximo item, progresso e tempo pelo painel remoto.",
          "Use Voltar, Reproduzir/Pausar e Avançar para conduzir a apresentação.",
          "No perfil Operador, estão disponíveis Projetar, Encerrar e os comandos de emergência.",
        ],
        warning: "Proteja o acesso com senha. O perfil Operador pode alterar diretamente o que o público vê.",
        moduleId: "config",
        actionLabel: "Abrir Controle remoto",
        keywords: ["celular", "operador", "apresentador", "perfil", "qr code", "progresso", "remoto"],
      },
      {
        id: "comandos-emergencia",
        title: "Use os comandos de emergência",
        summary: "Oculte, congele ou substitua temporariamente a projeção sem perder o conteúdo atual.",
        icon: "mdi-shield-alert-outline",
        details: [
          "Tela preta oculta imediatamente todo o conteúdo projetado.",
          "Congelar mantém na saída a imagem atual enquanto o operador prepara o próximo conteúdo.",
          "Logo substitui temporariamente a projeção pela identidade visual configurada.",
          "Normal remove o modo de emergência e restaura a apresentação ativa.",
        ],
        warning: "Os comandos de emergência ficam disponíveis no controle remoto apenas para o perfil Operador.",
        keywords: ["tela preta", "blackout", "congelar", "freeze", "logo", "emergência", "normal"],
      },
      {
        id: "automacao-liturgia",
        title: "Automatize ações pela liturgia",
        summary: "Dispare comandos da mesa Soundcraft Ui16 ao abrir itens do roteiro.",
        icon: "mdi-lightning-bolt-outline",
        steps: [
          "Abra Configurações > Automação e ative os gatilhos.",
          "Cadastre a conexão da Soundcraft Ui16 e crie ações como volume, mute ou desmute.",
          "Na Liturgia, edite um item compatível e selecione o gatilho de automação.",
          "Ao abrir o item durante o culto, confirme que a ação foi executada na mesa.",
          "Faça um ensaio completo e mantenha uma forma de controle manual disponível.",
        ],
        warning: "Automação de áudio altera o som ao vivo. Teste canais, níveis e conexão fora do horário da programação.",
        moduleId: "config",
        actionLabel: "Configurar Automação",
        keywords: ["soundcraft", "ui16", "mesa", "automação", "gatilho", "mute", "volume", "liturgia"],
      },
      {
        id: "atalhos-apresentacao",
        title: "Controle slides com atalhos globais",
        summary: "Avance ou retorne mesmo quando a janela de projeção estiver em destaque.",
        icon: "mdi-keyboard-outline",
        details: [
          "Seta para a direita ou para baixo avança a apresentação.",
          "Seta para a esquerda ou para cima retorna ao item anterior.",
          "Os atalhos globais são habilitados enquanto uma apresentação compatível está ativa.",
          "Em apresentações de PDF, a barra de espaço também pode avançar quando o painel de controle está em foco.",
        ],
        keywords: ["setas", "global", "avançar", "voltar", "slide", "espaço", "pdf"],
      },
    ],
  },  {
    id: "atalhos",
    title: "Atalhos de teclado",
    description: "Acesse rapidamente as ações mais frequentes.",
    icon: "mdi-keyboard-outline",
    topics: [
      {
        id: "atalhos-gerais",
        title: "Atalhos gerais",
        summary: "Navegue sem interromper a operação.",
        icon: "mdi-keyboard-settings-outline",
        details: [
          "Ctrl+H — Página Inicial.",
          "Ctrl+F — buscar músicas.",
          "Ctrl+B — abrir a Bíblia.",
          "Ctrl+L — Biblioteca Local.",
          "Ctrl+, — Configurações.",
          "Esc — encerrar ou ocultar a projeção ativa.",
        ],
        tips: ["No macOS, use Command no lugar de Ctrl nos atalhos do menu."],
        keywords: ["ctrl", "command", "teclado", "hotkey", "esc"],
      },
      {
        id: "atalhos-biblia",
        title: "Atalhos da Bíblia",
        summary: "Navegue pelos versos diretamente pelo teclado.",
        icon: "mdi-arrow-left-right",
        details: ["Seta esquerda — verso anterior.", "Seta direita — próximo verso.", "Delete — limpar a projeção bíblica."],
        keywords: ["seta", "anterior", "próximo", "delete", "verso"],
      },
    ],
  },
  {
    id: "solucoes",
    title: "Solução de problemas",
    description: "Resolva as situações mais comuns durante a operação.",
    icon: "mdi-lifebuoy",
    topics: [
      {
        id: "projecao-nao-aparece",
        title: "A projeção não aparece na tela correta",
        summary: "Confira cabo, modo de exibição e monitor selecionado.",
        icon: "mdi-monitor-off",
        steps: [
          "Confirme que cabo e projetor estão ligados.",
          "No sistema operacional, use o modo Estender.",
          "Em Configurações > Projeção, selecione novamente a saída.",
          "Encerre a projeção atual e teste novamente.",
          "Se a tela foi conectada depois, reinicie o aplicativo.",
        ],
        moduleId: "config",
        actionLabel: "Revisar Projeção",
        keywords: ["sem imagem", "monitor errado", "hdmi", "projetor", "tela preta"],
      },
      {
        id: "audio-nao-toca",
        title: "O áudio não toca",
        summary: "Revise volume, dispositivo padrão e sistema de som.",
        icon: "mdi-volume-off",
        steps: [
          "Confirme que o player não está pausado ou sem volume.",
          "Verifique o volume do sistema operacional.",
          "Selecione a saída correta no sistema e no equipamento.",
          "Reabra a mídia após trocar o dispositivo e teste outro arquivo.",
        ],
        keywords: ["som", "volume", "mudo", "caixa", "hdmi", "player"],
      },
      {
        id: "conteudo-indisponivel",
        title: "Uma música ou mídia está indisponível",
        summary: "Sincronize a biblioteca ou confirme o arquivo local.",
        icon: "mdi-file-alert-outline",
        steps: [
          "Conecte-se à internet e abra Biblioteca Local.",
          "Sincronize o conteúdo e aguarde a conclusão.",
          "Tente abrir o item novamente.",
          "Para mídia externa, confirme que o arquivo não foi movido ou removido.",
        ],
        moduleId: "sync",
        actionLabel: "Sincronizar Biblioteca",
        keywords: ["não encontrado", "arquivo", "download", "sincronização", "offline"],
      },
      {
        id: "remoto-nao-conecta",
        title: "O controle remoto não conecta",
        summary: "Confira servidor, rede, endereço, senha e firewall.",
        icon: "mdi-wifi-alert",
        steps: [
          "Confirme que o servidor está ativo.",
          "Verifique se os dispositivos estão na mesma rede.",
          "Use um endereço atualmente exibido nas configurações.",
          "Revise a senha e tente novamente pelo QR Code.",
          "Confira se o firewall permite acesso à rede local.",
        ],
        moduleId: "config",
        actionLabel: "Revisar Controle remoto",
        keywords: ["wifi", "firewall", "porta", "qr code", "celular", "servidor"],
      },
      {
        id: "checklist",
        title: "Checklist antes do culto",
        summary: "Uma revisão curta evita a maioria das interrupções.",
        icon: "mdi-clipboard-check-outline",
        details: [
          "Teste projetor, retorno e sistema de som.",
          "Abra músicas, apresentações e vídeos planejados.",
          "Revise a liturgia e a ordem dos itens.",
          "Confirme o controle remoto, se usado.",
          "Desative notificações e conecte o computador à energia.",
          "Mantenha um operador responsável presente.",
        ],
        keywords: ["checklist", "preparar", "culto", "teste", "energia", "notificações"],
      },
    ],
  },
];
